# Purpose: Helm template: external-secrets.
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.env.awsRegion | quote }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secrets-credentials
            key: AWS_ACCESS_KEY_ID
          secretAccessKeySecretRef:
            name: aws-secrets-credentials
            key: AWS_SECRET_ACCESS_KEY
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fieldflow-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: fieldflow-secrets
    creationPolicy: Owner
  data:
    - secretKey: AUTH_JWT_SECRET
      remoteRef:
        key: {{ .Values.env.secretsManagerKey | quote }}
        property: AUTH_JWT_SECRET
    - secretKey: INTERNAL_EVENT_SECRET
      remoteRef:
        key: {{ .Values.env.secretsManagerKey | quote }}
        property: INTERNAL_EVENT_SECRET
    - secretKey: WS_AUTH_TOKEN
      remoteRef:
        key: {{ .Values.env.secretsManagerKey | quote }}
        property: WS_AUTH_TOKEN
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.env.secretsManagerKey | quote }}
        property: DATABASE_URL
