apiVersion: v1
kind: Service
metadata:
  name: read-service
spec:
  ports:
    - port: 3003
      targetPort: 3003
  selector:
    app: read-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: read-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: read-service
  template:
    metadata:
      labels:
        app: read-service
    spec:
      containers:
        - name: read-service
          image: fieldflow/read-service:latest
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: "3003"
            - name: DATABASE_URL
              value: postgres://postgres:postgres@postgres:5432/fieldflow
            - name: AUTH_JWT_SECRET
              value: supersecret
            - name: GATEWAY_URL
              value: http://api-gateway:3000
